In [6]:
import numpy as np
from scipy.sparse import csc_matrix
from l0learn.models import FitModel

In [7]:
def sample_FitModel(loss: str = 'SquaredError', intercept: bool = True, penalty: str = 'L0L1'):
    i = intercept
    beta1 = csc_matrix([[0, 0],
                        [1, 2]])
    beta2 = csc_matrix([[0],
                        [3]])
    beta3 = csc_matrix([[0, 0, 0],
                        [4, 5, 6]])

    return FitModel(settings={'loss': loss, 'intercept': intercept, 'penalty': penalty},
                    lambda_0=[[10, 5], [10], [10, 5, 0]],
                    gamma=[2, 1, 0],
                    support_size=[[0, 1], [3], [4, 5, 6]],
                    coeffs=[beta1, beta2, beta3],
                    intercepts=[[-1*i, -2*i], [-3*i], [-4*i, -5*i, -6*i]],
                    converged=[[True, True], [False], [True, False, True]])

In [9]:
f = sample_FitModel()

In [29]:
np.tile(np.arange(1, 7), (2, 1))

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [19]:
f.coeff().toarray()

array([[-1, -2, -3, -4, -5, -6],
       [ 0,  0,  0,  0,  0,  0],
       [ 1,  2,  3,  4,  5,  6]])

In [25]:
f.predict(np.array([[1, 2]]))

array([[1., 2., 3., 4., 5., 6.]])

In [11]:
f.predict(np.ones([2,2]))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.isrealobj(values[0])

True

In [11]:
for i, value in enumerate(values):
    if not isinstance(value, np.ndarray) or value.ndim != 1 or not np.isrealobj(value):
        print(value)

In [8]:
# csc_arr = csc_matrix((data, indices, indptr), shape=(5, 5)).toarray()
csc_arr = csc_matrix(arr)

In [9]:
csc_arr.data

array([0.76355643, 0.99015561, 0.96518113, 0.9159315 , 0.76160812])